compile:
	gcc -o test test.c
test:
	echo "hello"
test.c:
	echo "#include <stdio.h>\n int main()\n { \n printf("\"hello"\");\n}">test.c
rem:
	rm test.c
run:
	./test



#arun@arun:~/practise/makefilecode/1_program$ vi Makefile
#arun@arun:~/practise/makefilecode/1_program$ make test.c
#make: 'test.c' is up to date.
#arun@arun:~/practise/makefilecode/1_program$ vi test.c
#arun@arun:~/practise/makefilecode/1_program$ make test.c
#make: 'test.c' is up to date.
#arun@arun:~/practise/makefilecode/1_program$ make run
#./test
#helloarun@arun:~/practise/makefilecode/1_program$
